// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Simulador2.Models;
using System;

namespace Simulador2.Migrations
{
    [DbContext(typeof(Simulador2Context))]
    partial class Simulador2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Simulador2.Models.Alumnos", b =>
                {
                    b.Property<long>("Idperfil")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApellidosM")
                        .IsRequired()
                        .HasMaxLength(85);

                    b.Property<string>("ApellidosP")
                        .IsRequired()
                        .HasMaxLength(85);

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(90);

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(6);

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasMaxLength(85);

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasMaxLength(110);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(85);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(85);

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(85);

                    b.Property<string>("NumTelefono")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.HasKey("Idperfil");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("Simulador2.Models.EstimacionServicios", b =>
                {
                    b.Property<long>("Idsuscripcion")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TotalMensual")
                        .IsRequired()
                        .HasMaxLength(85);

                    b.Property<int>("TotalSuscripciones")
                        .HasMaxLength(85);

                    b.Property<string>("unidad_produccion")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.HasKey("Idsuscripcion");

                    b.ToTable("EstimacionServicios");
                });
#pragma warning restore 612, 618
        }
    }
}
